POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/b640f3c1-de8a-4934-97fd-80326ed96e98/attendees
Content-Type: application/json

{
  "name": "João Vitor",
  "email": "jv.dossantos012@gmail.com"
}

###

GET http://localhost:3333/events/b640f3c1-de8a-4934-97fd-80326ed96e98
Content-Type: application/json

### 

GET http://localhost:3333/attendees/1/badge
Content-Type: application/json

###

GET http://localhost:3333/attendees/1/check-in
Content-Type: application/json

###

GET http://localhost:3333/events/b640f3c1-de8a-4934-97fd-80326ed96e98/attendees
Content-Type: application/json